---
title: "Meta-Data"
author: "Victoria Aroworade"
format: html
editor: visual
date: March 3, 2023
toc: true
toc-depth: 5
highlight-style: tango
theme: lux
code-fold: true
fig-width: 7
fig-height: 7
execute: 
  eval: true
  echo: true
  warning: false
  error: false
---

## Load Packages

```{r}
library(readxl)
library(openxlsx)
```

## Import Excel File

```{r}
meta_excel_file <- read_excel(path = "metadata/metadata_data/field_lists03mar2023.xlsx")
meta_excel_file
```

## Get sheet names

```{r}
excel_sheets(path = "metadata/metadata_data/field_lists03mar2023.xlsx")
```

## Create a vector of sheet names

```{r}
sheet_names <- c("Account", "Assay__c", "Instrument__c", "Software__c", "Technology_Submission__c", "Performance_Detail_Submission")
```

## Import data from multiple sheets by name

```{r}
data_by_names <- lapply(sheet_names, function(x)read_excel(path = "metadata/metadata_data/field_lists03mar2023.xlsx", sheet = x))
data_by_names
```

## Create a new workbook

## Add the data frames to separate tabs in workbook


